import { computed, onMounted, reactive, ref } from 'vue';
import { learningDiagnosisApi } from '../api/learningDiagnosis.js';

export function useLearningDiagnosis(currentUser, emit) {
    const session = ref(null), snapshot = ref(null), path = ref(null), pathHistory = ref([]), evidence = ref([]);
    const activeTask = ref(null), activePage = ref('home'), evidenceOpen = ref(false);
    const initializing = ref(true), loading = ref(false), error = ref(''), currentHintLevel = ref(0), currentHint = ref(null), lastExecution = ref(null);
    const code = ref(''), answer = ref('');
    const gitEnabled = ref(false), gitRiskOpen = ref(false), goalModalOpen = ref(false);
    const goalForm = reactive({ raw_goal_text: '', course_name: '', deadline: '', weekly_minutes: 180, self_reported_difficulty: '', reuse_existing_evidence: true });
    const studentId = computed(() => currentUser.value?.username || currentUser.value?.student_id || 'student-demo');
    const assessments = computed(() => snapshot.value?.assessments || []);
    const primaryAssessment = computed(() => assessments.value[0] || {});
    const tasks = computed(() => path.value?.tasks || []);
    const notify = (message, type = 'info') => emit?.('show-toast', message, type);
    const run = async (operation) => { loading.value = true; error.value = ''; try { return await operation(); } catch (err) { error.value = err?.message || '学习诊断服务暂时不可用'; notify(error.value, 'error'); return null; } finally { loading.value = false; } };
    const applyResult = (result) => { session.value = result?.session || session.value; snapshot.value = result?.snapshot || snapshot.value; path.value = result?.path || result?.paths?.at?.(-1) || path.value; if (result?.paths) pathHistory.value = result.paths; evidence.value = result?.evidence || evidence.value; };
    const loadLatestSession = async () => { try { const result = await learningDiagnosisApi.getLatestSession(studentId.value); applyResult(result); return result; } catch (err) { if (err?.status !== 404) { error.value = err?.message || '学习诊断服务暂时不可用'; notify(error.value, 'error'); } return null; } finally { initializing.value = false; } };
    const createSession = (payload = {}) => run(async () => { const result = await learningDiagnosisApi.createSession({ student_id: studentId.value, course: payload.course_name || '数据结构', ...payload, include_git_evidence: gitEnabled.value }); applyResult(result); notify('学习诊断已生成', 'success'); return result; });
    const openGoalModal = () => { Object.assign(goalForm, { raw_goal_text: session.value?.goal?.raw_goal_text || '', course_name: session.value?.goal?.course_name || session.value?.goal?.course || '', deadline: session.value?.goal?.deadline || '', weekly_minutes: session.value?.goal?.weekly_minutes || 180, self_reported_difficulty: session.value?.goal?.self_reported_difficulty || '', reuse_existing_evidence: true }); goalModalOpen.value = true; };
    const updateGoal = () => run(async () => { const hadSession = Boolean(session.value); const payload = { student_id: studentId.value, ...goalForm }; const result = session.value ? learningDiagnosisApi.updateGoal(session.value.id, payload) : learningDiagnosisApi.createSession({ course: goalForm.course_name || '数据结构', ...payload, include_git_evidence: false }); applyResult(await result); goalModalOpen.value = false; notify(hadSession ? '学习目标与动态路径已更新' : '学习目标与动态路径已生成', 'success'); return result; });
    const refreshDiagnosis = () => run(async () => { const result = await learningDiagnosisApi.refreshSession(session.value.id, studentId.value, { trigger_type: 'MANUAL_REFRESH' }); applyResult(result); notify('诊断快照与学习路径已更新', 'success'); return result; });
    const openTaskByType = (task) => { activeTask.value = task; currentHintLevel.value = 0; currentHint.value = null; lastExecution.value = null; code.value = task?.content_payload?.starter_code || task?.starter_code || ''; answer.value = ''; const type = String(task?.task_type || '').toUpperCase(); activePage.value = type === 'KNOWLEDGE_REVIEW' ? 'knowledge' : type === 'GUIDED_PRACTICE' ? 'guided' : type === 'CODING_PRACTICE' ? 'coding' : type === 'INDEPENDENT_RETEST' ? 'retest' : 'coding'; };
    const openTask = openTaskByType;
    const loadPathHistory = () => run(async () => { const result = await learningDiagnosisApi.getPath(session.value.id, studentId.value); pathHistory.value = result?.paths || []; return pathHistory.value; });
    const openVersion = async () => { await loadPathHistory(); activePage.value = 'version'; };
    const goHome = () => { activePage.value = 'home'; };
    const clearExecution = () => { lastExecution.value = null; currentHint.value = null; };
    const updateTaskCode = (value) => { code.value = value; clearExecution(); };
    const resetTaskCode = () => { code.value = activeTask.value?.content_payload?.starter_code || activeTask.value?.starter_code || ''; clearExecution(); };
    const runTaskCode = (payload = {}) => run(async () => { const result = await learningDiagnosisApi.runTask(activeTask.value.task_id, { student_id: studentId.value, session_id: session.value.id, code: payload.code ?? code.value, language: activeTask.value?.content_payload?.contract?.language || 'python' }); lastExecution.value = result; notify(result.status === 'PASSED' ? '全部公开测试已通过' : '运行结束，请查看测试结果', result.status === 'PASSED' ? 'success' : 'info'); return result; });
    const requestHint = () => run(async () => { const level = Math.min(currentHintLevel.value + 1, activeTask.value?.task_type === 'INDEPENDENT_RETEST' ? 1 : 5); const attempt = { code: code.value, execution: lastExecution.value }; const result = await learningDiagnosisApi.requestHint(activeTask.value.task_id, session.value.id, studentId.value, level, activeTask.value.task_type === 'INDEPENDENT_RETEST', attempt); currentHintLevel.value = result.approved_level ?? level; currentHint.value = result; notify(`已授权 Level ${currentHintLevel.value} 提示`, 'info'); return result; });
    const submitTask = (payload = {}) => run(async () => { const result = await learningDiagnosisApi.submitTask(activeTask.value.task_id, { student_id: studentId.value, session_id: session.value.id, code: payload.code ?? code.value, answer: payload.answer ?? answer.value, hint_level: currentHintLevel.value, assessment_mode: activeTask.value.task_type === 'INDEPENDENT_RETEST' }); lastExecution.value = result.execution || lastExecution.value; applyResult(result); notify(result.execution?.status === 'PASSED' ? '任务通过，学习诊断已更新' : '已记录本次尝试并调整学习路径', result.execution?.status === 'PASSED' ? 'success' : 'info'); return result; });
    const confirmGit = () => run(async () => { const result = await learningDiagnosisApi.toggleGitEvidence(session.value.id, studentId.value, true); gitEnabled.value = true; gitRiskOpen.value = false; applyResult(result); notify('Git 实践证据已纳入分析', 'success'); return result; });
    const toggleGit = () => { if (gitEnabled.value) { const previous = gitEnabled.value; gitEnabled.value = false; learningDiagnosisApi.toggleGitEvidence(session.value.id, studentId.value, false).then((result) => { applyResult(result); notify('Git 实践证据已关闭', 'info'); }).catch((err) => { gitEnabled.value = previous; notify(`Git 证据关闭失败：${err?.message || '请稍后重试'}`, 'error'); }); } else gitRiskOpen.value = true; };
    onMounted(() => loadLatestSession());
    return { session, snapshot, path, pathHistory, evidence, activeTask, activePage, evidenceOpen, initializing, loading, error, currentHintLevel, currentHint, lastExecution, code, answer, gitEnabled, gitRiskOpen, goalModalOpen, goalForm, studentId, primaryAssessment, tasks, createSession, loadLatestSession, loadPathHistory, openGoalModal, updateGoal, refreshDiagnosis, openTask, openTaskByType, openVersion, goHome, clearExecution, updateTaskCode, resetTaskCode, runTaskCode, requestHint, submitTask, confirmGit, toggleGit };
}
