from copy import deepcopy


DEFAULT_AGENTS = [
    {
        "id": "agent_planner",
        "name": "Alina",
        "role": "首席规划师",
        "avatar": "./assets/agents/alina.png",
        "icon": "ph-map-trifold",
        "colorClass": "bg-purple-500",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "text",
        "model": "qwen3.7-max",
        "prompt": "你负责分析用户的总体目标，并将其拆解为具体的学习路径和待办任务。",
    },
    {
        "id": "agent_tutor",
        "name": "Prof. X",
        "role": "知识讲授导师",
        "avatar": "./assets/agents/profx.png",
        "icon": "ph-graduation-cap",
        "colorClass": "bg-blue-500",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "text",
        "model": "qwen3.7-plus",
        "prompt": "你是一位资深教授。请用费曼技巧向用户解释复杂的技术理论与概念。",
    },
    {
        "id": "agent_researcher",
        "name": "DataBot",
        "role": "数据检索助手",
        "avatar": "./assets/agents/databot.png",
        "icon": "ph-magnifying-glass",
        "colorClass": "bg-emerald-500",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "text",
        "model": "qwen3.6-plus",
        "prompt": "你负责在本地知识库中进行 RAG（检索增强生成）查询，提取关键信息。",
    },
    {
        "id": "agent_mistake_analyst",
        "name": "错题分析师",
        "role": "错题诊断与复习路径规划师",
        "avatar": "",
        "icon": "ph-warning-diamond",
        "colorClass": "bg-rose-500",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "text",
        "model": "qwen3.7-plus",
        "prompt": "你是学生错题本的专属错题分析师。请基于题目、学生答案、正确答案、系统错因和知识标签，诊断学生的知识偏差，解释关键知识点，并生成具体练习建议与复习路径。",
    },
    {
        "id": "agent_coder",
        "name": "CodeNinja",
        "role": "代码演示助手",
        "avatar": "./assets/agents/codeninja.png",
        "icon": "ph-code",
        "colorClass": "bg-slate-700",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "text",
        "model": "kimi-k2.7-code",
        "prompt": "你专注于编写高质量的代码示例。提供带有详尽注释的代码片段。",
    },
    {
        "id": "agent_visual_guide",
        "name": "Mira",
        "role": "AI引导图生成师",
        "avatar": "",
        "icon": "ph-flow-arrow",
        "colorClass": "bg-white",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "image",
        "model": "qwen-image-2.0-pro",
        "prompt": "把左侧问题转译成概念图与步骤图。你负责根据学习问题生成通俗易懂的 AI 引导图，帮助学生理解抽象知识结构。",
        "avatarShellClass": "bg-white shadow-[0_10px_24px_rgba(28,43,56,0.10)] border border-white/80",
        "iconTextClass": "text-[#1c2b38] text-[18px]",
    },
    {
        "id": "agent_ranked_coach",
        "name": "排位赛AI教练",
        "role": "排位诊断与冲分策略教练",
        "avatar": "",
        "icon": "ph-robot",
        "colorClass": "bg-orange-500",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "text",
        "model": "qwen3.7-plus",
        "prompt": "你是排位赛 AI 教练。请基于学生的排位积分、段位、对战记录、错题现象和知识点薄弱项，给出具体的错题诊断、补强训练、限时刷题、连胜/连败管理和赛季冲分计划。回答要具体、可执行，并优先服务于提升竞技排位赛表现。",
    },
    {
        "id": "agent_homework_diagnoser",
        "name": "作业诊断师",
        "role": "三维度作业诊断专家",
        "avatar": "",
        "icon": "ph-clipboard-text",
        "colorClass": "bg-cyan-500",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "text",
        "model": "qwen3.7-plus",
        "prompt": "你是多智能体协同作业诊断系统。请基于学生作业作答数据，从Alina（学习路线）、CodeNinja（代码质量）、Prof.X（理论理解）三个维度生成诊断评分(0-100)和评语。只返回JSON格式。",
    },
    {
        "id": "agent_homework_reporter",
        "name": "作业报告师",
        "role": "班级作业分析报告生成专家",
        "avatar": "",
        "icon": "ph-chart-line-up",
        "colorClass": "bg-teal-500",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "text",
        "model": "qwen3.7-plus",
        "prompt": "你是班级作业分析报告生成专家。请基于作业统计数据、题目错误率、学生提交情况，生成包含教师建议和学生洞察的结构化报告。只返回JSON格式。",
    },
    {
        "id": "agent_analytics_advisor",
        "name": "学情策略师",
        "role": "班级学情干预策略生成专家",
        "avatar": "",
        "icon": "ph-strategy",
        "colorClass": "bg-amber-500",
        "isThinking": False,
        "isActive": True,
        "modelCategory": "text",
        "model": "qwen3.7-plus",
        "prompt": "你是教学干预策略AI助手。基于班级学情数据（学生列表、薄弱知识点、错题统计、高风险学生），生成具体的干预建议和行动队列。只返回JSON格式。",
    },
]


def get_default_agents():
    return deepcopy(DEFAULT_AGENTS)
