export default {
  name: 'LearningIndependentRetestPage',
  props: { task: { type: Object, default: null }, code: { type: String, default: '' }, hintLevel: { type: Number, default: 0 }, hint: { type: Object, default: null }, execution: { type: Object, default: null }, loading: Boolean },
  emits: ['back', 'hint', 'run', 'reset', 'submit', 'update:code'],
  data() { return { resultTab: 'tests', answer: '' }; },
  computed: {
    payload() { return this.task?.content_payload || {}; },
    title() { return this.task?.title || '独立复测 · 多边界场景变式题'; },
    knowledgePointName() { return this.payload.knowledge_point_name || this.task?.knowledge_point_ids?.[0] || '当前知识点'; },
    languageLabel() { return String(this.payload.contract?.language || 'python').toLowerCase() === 'javascript' ? 'JavaScript' : 'Python 3'; },
    cases() {
      const labels = ['普通场景 NORMAL', '边界场景 BOUNDARY', '异常场景 EXCEPTION'];
      const descriptions = ['验证常规输入下的基本逻辑', '验证空值、单节点等边界', '验证非法输入与异常处理'];
      const source = Array.isArray(this.payload.test_cases) ? this.payload.test_cases : [];
      return labels.map((label, index) => ({ id: index + 1, label, description: descriptions[index], input: source[index]?.input || '', expected: source[index]?.expected || '' }));
    },
    lineNumbers() { return Array.from({ length: Math.max(12, String(this.code || '').split('\n').length) }, (_, index) => index + 1); },
    hasExecution() { return Boolean(this.execution?.execution_id || this.execution?.status); },
    executionPassed() { return this.execution?.status === 'PASSED'; },
    testSummary() { return this.execution?.test_summary || { total: 3, passed: 0, failed: 0 }; },
    displayCases() { return this.cases.map((item, index) => { const result = this.execution?.test_cases?.[index]; return { ...item, passed: result ? Boolean(result.passed) : null, actual: result?.actual || '', error: result?.error || '' }; }); },
    statusLabel() { if (!this.hasExecution) return '待验证'; if (this.executionPassed) return '全部通过'; if (this.execution?.status === 'TEST_FAILED') return '存在失败用例'; return '运行未完成'; },
    hintText() { return this.hint?.content || '独立复测阶段不开放分步答案提示，只反馈测试是否覆盖目标场景。'; }
  },
  methods: {
    submitAnswer() { const { answer } = this; this.$emit('submit', { answer }); },
    updateCode(value) { this.$emit('update:code', value); },
    runCode() { if (!this.loading && this.code.trim()) this.$emit('run', { code: this.code }); },
    submitCode() { if (!this.loading && this.code.trim()) this.$emit('submit', { code: this.code }); }
  },
  template: `
  <section aria-label="Learning diagnosis / Independent retest" class="h-full overflow-y-auto bg-[#eef2f4] p-4 lg:p-6"><input v-model="answer" type="hidden" aria-hidden="true"><div class="max-w-[1360px] mx-auto">
    <div class="flex items-center justify-between gap-4 mb-4"><button aria-label="back-to-learning-diagnosis" class="text-xs font-bold text-slate-600" @click="$emit('back')">← 返回学习诊断　/　独立复测</button><span class="px-3 py-1.5 rounded-full bg-white border border-[#b91c1c]/30 text-[#b91c1c] text-[10px] font-bold">诊断会话进行中</span></div>
    <section data-testid="independent-retest-page" class="bg-white rounded-[22px] border border-white shadow-soft overflow-hidden">
      <header class="px-5 lg:px-7 py-5 border-b border-slate-200 grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_470px] gap-6"><div><p class="text-[10px] uppercase tracking-[0.22em] text-slate-500 font-bold">LEARNING DIAGNOSIS / INDEPENDENT RETEST</p><h1 class="text-2xl lg:text-3xl font-bold text-[#1c2b38] mt-2" style="font-family:'Noto Serif SC',serif">{{ title }}</h1><p class="text-xs text-slate-500 mt-2">请独立完成复测，系统将根据多场景表现更新掌握度与置信度。</p><div class="flex flex-wrap gap-2 mt-4"><span class="px-2.5 py-1 rounded-full bg-red-50 text-[#a32923] text-[10px] font-bold">当前首要任务</span><span class="px-2.5 py-1 rounded-full bg-[#edf3f5] text-[#456170] text-[10px] font-bold">预计 {{ task?.estimated_minutes || 20 }} 分钟</span><span class="px-2.5 py-1 rounded-full bg-[#edf3f5] text-[#456170] text-[10px] font-bold">{{ languageLabel }}</span><span class="px-2.5 py-1 rounded-full bg-amber-50 text-amber-700 text-[10px] font-bold">禁止获取答案提示</span></div></div><div class="self-center"><div class="flex justify-between text-[10px] text-slate-400"><span>理解题意</span><span>编写代码</span><span class="text-[#a32923] font-bold">独立复测</span><span>更新诊断</span></div><div class="h-1.5 rounded-full bg-slate-200 mt-3 overflow-hidden"><div class="h-full bg-[#b91c1c] rounded-full w-3/4"></div></div></div></header>
      <div class="grid grid-cols-1 xl:grid-cols-[315px_minmax(0,1fr)_358px] min-h-[650px]">
        <aside class="bg-[#fbfcfc] p-5 xl:border-r border-slate-200"><h2 class="text-xl font-bold text-[#1c2b38]">复测目标</h2><p class="text-xs text-slate-500 mt-2">{{ knowledgePointName }} · 独立验证</p><div class="mt-4 rounded-xl border border-red-200 bg-red-50 p-3"><p class="text-[11px] font-bold text-red-700">本任务用于独立验证</p><p class="text-[10px] text-slate-500 mt-1">提示仅保留规则说明</p></div><h3 class="text-[11px] font-bold text-slate-800 mt-6">场景覆盖要求</h3><article v-for="item in cases" :key="item.id" class="py-4 border-b border-slate-200"><p class="text-xs font-bold text-[#1c2b38]">{{ item.id }}　{{ item.label }}</p><p class="text-[10px] text-slate-500 mt-1">{{ item.description }}</p></article><p class="text-[10px] text-slate-400 mt-8">覆盖结果将在提交后写入诊断证据</p></aside>
        <main class="min-w-0 bg-[#f4f7f8] p-4"><section class="rounded-2xl overflow-hidden bg-[#121d28]"><div class="h-11 px-4 flex items-center justify-between bg-[#1b2b39] text-[10px] text-slate-100"><span class="font-mono">solution.py · 独立复测</span><span>{{ languageLabel }}</span></div><div class="grid grid-cols-[42px_minmax(0,1fr)] min-h-[430px]"><div class="py-4 pr-3 text-right bg-[#101a24] text-[11px] leading-[22px] text-slate-600 font-mono"><div v-for="number in lineNumbers" :key="number">{{ number }}</div></div><textarea :value="code" @input="updateCode($event.target.value)" spellcheck="false" aria-label="learning-diagnosis-independent-retest-editor" class="w-full min-h-[430px] resize-none bg-[#121d28] text-slate-100 p-4 outline-none font-mono text-xs leading-[22px]"></textarea></div><footer class="min-h-[58px] px-3 py-2 bg-white flex justify-end gap-2"><button aria-label="reset-independent-retest" class="min-h-[36px] px-3 rounded-xl border text-[10px] font-bold" @click="$emit('reset')">重置代码</button><button aria-label="run-independent-retest" :disabled="loading || !code.trim()" class="min-h-[36px] px-4 rounded-xl bg-[#1c2b38] text-white text-[10px] font-bold" @click="runCode">运行验证</button><button aria-label="submit-independent-retest" :disabled="loading || !code.trim()" class="min-h-[36px] px-4 rounded-xl bg-[#b91c1c] text-white text-[10px] font-bold" @click="submitCode">提交独立复测</button></footer></section><section class="rounded-2xl bg-white border border-slate-200 mt-3 min-h-[150px]"><div class="h-10 px-4 border-b flex items-center justify-between"><div class="flex gap-5 text-[10px]"><button :class="resultTab === 'tests' ? 'text-[#b91c1c] font-bold' : ''" @click="resultTab='tests'">测试结果</button><button :class="resultTab === 'history' ? 'text-[#b91c1c] font-bold' : ''" @click="resultTab='history'">运行记录</button></div><span class="text-[9px]">{{ statusLabel }}<template v-if="hasExecution"> · {{ testSummary.passed || 0 }} / {{ testSummary.total || 0 }} 通过</template></span></div><div v-if="resultTab === 'tests'" class="grid grid-cols-1 sm:grid-cols-3 gap-2 p-3"><article v-for="item in displayCases" :key="item.id" class="rounded-xl border p-3"><p class="text-[10px] font-bold">{{ item.passed === true ? '✓' : item.passed === false ? '×' : '—' }} {{ item.label }}</p><p class="text-[9px] text-slate-500 mt-2">{{ item.passed === null ? '待验证' : item.error || item.actual || '已通过' }}</p></article></div><div v-else class="p-4 text-[10px] text-slate-500">最近一次运行记录：{{ hasExecution ? execution.execution_id : '当前还没有运行记录。' }}</div></section></main>
        <aside class="bg-[#f4f7f8] p-5"><section class="rounded-2xl bg-[#1c2b38] text-white p-5"><p class="text-[10px] uppercase tracking-[0.2em] text-white/50 font-bold">INDEPENDENT AGENT</p><h3 class="text-sm font-bold mt-4">Prof. X · 复测监考官</h3><p class="text-[10px] text-white/60 mt-2">只反馈测试覆盖，不提供分步答案</p><div class="rounded-xl bg-white/[.07] p-4 mt-4"><p class="text-[10px] font-bold">提示已锁定</p><p class="text-[10px] text-white/60 mt-2">{{ hintText }}</p></div><div class="rounded-xl bg-white p-4 mt-3 text-[#1c2b38]"><p class="text-[10px] font-bold">证据写入规则</p><p class="text-[10px] text-slate-500 mt-2">结果将作为独立证据参与掌握度计算</p></div></section><section class="rounded-2xl bg-amber-50 border border-amber-200 p-4 mt-4"><p class="text-[10px] font-bold text-amber-800">独立性保护</p><p class="text-[10px] text-amber-700 leading-5 mt-2">系统不会直接展示标准答案。正式提交结果才会影响本次学习诊断。</p></section></aside>
      </div><footer class="min-h-[40px] px-4 border-t border-slate-200 bg-white flex items-center justify-center text-[9px] text-slate-400">运行结果只用于调试；点击“提交独立复测”后才更新学习证据与动态路径。</footer>
    </section></div>
  </section>`
};
